"""empty message

Revision ID: 428567de4f25
Revises: 
Create Date: 2022-09-25 13:06:12.857505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428567de4f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flask-pengguna', sa.Column('hak_akses', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flask-pengguna', 'hak_akses')
    # ### end Alembic commands ###
